services:
  agent:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: agent
    ports:
      - 8080:8080
    tty: true
    command: python -m deeppavlov_agent.run -p 8080 -ch http_client --cors
version: "3.7"
